-- =====================================================
-- DATA SQL - Samsung Merchandising API
-- =====================================================

-- 1. UTILISATEURS
-- Aucune donnée utilisateur n'est insérée automatiquement.
-- Créez les comptes (SUPERVISOR / SFOS / PROMOTER) via l'API ou l'interface Team.

-- 2. MAGASINS (Vrais lieux à Casa) - ces données sont conservées
INSERT INTO stores (name, type, city, latitude, longitude, address) VALUES
('ElectroPlanet Marjane Californie', 'OR', 'Casablanca', 33.5552, -7.6328, 'Centre Commercial Marjane Californie'),
('Cosmos Morocco Mall', 'OR', 'Casablanca', 33.5768, -7.7077, 'Morocco Mall, Bd de l''Océan'),
('Biougnach Aïn Sebaâ', 'OR', 'Casablanca', 33.6080, -7.5300, 'Route de Rabat'),
('Samsung Store Maarif', 'OR', 'Casablanca', 33.5869, -7.6323, 'Rue Ali Abderrazak'),
('Revendeur Derb Ghallef 1', 'IR', 'Casablanca', 33.5785, -7.6250, 'Derb Ghallef, Kiosque 12'),
('Marjane Hay Hassani', 'OR', 'Casablanca', 33.5650, -7.6650, 'Hay Hassani');

-- 3. VISITES
-- Aucune visite n'est insérée automatiquement. Utilisez l'API /visits ou l'interface pour créer des visites.

-- 4. PRODUITS
-- Aucun produit n'est inséré automatiquement. Utilisez l'API /products ou l'interface Produits pour créer des produits.
-- =====================================================
-- DATA SQL - Samsung Merchandising API
-- =====================================================

-- 1. UTILISATEURS
-- Note: Users are now seeded by DataInitializer.java
-- It creates 6 SFOS and 50 Promoters with proper hierarchy
-- This section is kept empty to let DataInitializer handle user creation

-- 2. MAGASINS (Vrais lieux à Casa)
INSERT INTO stores (name, type, city, latitude, longitude, address) VALUES
('ElectroPlanet Marjane Californie', 'OR', 'Casablanca', 33.5552, -7.6328, 'Centre Commercial Marjane Californie'),
('Cosmos Morocco Mall', 'OR', 'Casablanca', 33.5768, -7.7077, 'Morocco Mall, Bd de l''Océan'),
('Biougnach Aïn Sebaâ', 'OR', 'Casablanca', 33.6080, -7.5300, 'Route de Rabat'),
('Samsung Store Maarif', 'OR', 'Casablanca', 33.5869, -7.6323, 'Rue Ali Abderrazak'),
('Revendeur Derb Ghallef 1', 'IR', 'Casablanca', 33.5785, -7.6250, 'Derb Ghallef, Stand 12'),
('Marjane Hay Hassani', 'OR', 'Casablanca', 33.5650, -7.6650, 'Hay Hassani');

-- 3. VISITES
-- Note: Visits are created dynamically through the application
-- The old visits data has been removed because user IDs are now generated by DataInitializer
-- You can create visits through the API or add them manually after users are created

-- 4. PRODUITS
-- Aucun produit n'est inséré automatiquement. Utilisez l'API /products ou l'interface Produits pour créer des produits.
